# Generated by Django 3.0.1 on 2021-04-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210404_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='score',
        ),
    ]
