# Generated by Django 3.1.7 on 2021-05-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
