# Generated by Django 3.0.1 on 2021-04-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='image',
            new_name='product',
        ),
    ]
